#!/bin/bash
set -e

echo "Creating databases: $DB_DATABASE and $DB_DATABASE_TEST"

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\`;
    CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE_TEST\`;
    GRANT ALL PRIVILEGES ON \`$DB_DATABASE\`.* TO '$DB_USERNAME'@'%';
    GRANT ALL PRIVILEGES ON \`$DB_DATABASE_TEST\`.* TO '$DB_USERNAME'@'%';
    FLUSH PRIVILEGES;
EOSQL
